//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synnduit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synnduit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains duplicate elements..
        /// </summary>
        internal static string ArgumentContainsDuplicates {
            get {
                return ResourceManager.GetString("ArgumentContainsDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GUID value must be specified..
        /// </summary>
        internal static string ArgumentMustNotBeEmptyGuid {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be specified..
        /// </summary>
        internal static string ArgumentMustNotBeWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not represent a valid GUID..
        /// </summary>
        internal static string ArgumentNotGuid {
            get {
                return ResourceManager.GetString("ArgumentNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument exceed the maximum allowable length of {0}..
        /// </summary>
        internal static string ArgumentTooLong {
            get {
                return ResourceManager.GetString("ArgumentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one source system must be specified..
        /// </summary>
        internal static string AtLeastOneSourceSystemMustBeSpecified {
            get {
                return ResourceManager.GetString("AtLeastOneSourceSystemMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dependency container has been set..
        /// </summary>
        internal static string DependencyContainerNotSet {
            get {
                return ResourceManager.GetString("DependencyContainerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency container has returned a null reference..
        /// </summary>
        internal static string DependencyContainerReturnedNull {
            get {
                return ResourceManager.GetString("DependencyContainerReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency container has thrown an exception; see inner exception for details..
        /// </summary>
        internal static string DependencyContainerThrewException {
            get {
                return ResourceManager.GetString("DependencyContainerThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value exceeds the maximum EntityIdentifier length of {0}..
        /// </summary>
        internal static string EntityIdentifierTooLong {
            get {
                return ResourceManager.GetString("EntityIdentifierTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not represent a valid match weight..
        /// </summary>
        internal static string InvalidMatchWeight {
            get {
                return ResourceManager.GetString("InvalidMatchWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; cannot be converted to {1}..
        /// </summary>
        internal static string ParameterCannotBeConvertedToEnum {
            get {
                return ResourceManager.GetString("ParameterCannotBeConvertedToEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permanent dependency container has been set..
        /// </summary>
        internal static string PermanentDependencyContainerSet {
            get {
                return ResourceManager.GetString("PermanentDependencyContainerSet", resourceCulture);
            }
        }
    }
}
